# Generated by Django 3.0.6 on 2020-10-13 09:10

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0005_student'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='petition',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='petition.Student'),
        ),
    ]
