# Generated by Django 3.0.6 on 2020-10-14 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0007_auto_20201013_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='petition.Student'),
        ),
    ]
