# Generated by Django 3.0.6 on 2020-10-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0008_auto_20201014_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='category',
            field=models.CharField(choices=[('Ensitu', 'Ensitu'), ('Department', 'Department'), ('EnsituDirector', 'EnsituDirector'), ('Advisor', 'Advisor')], max_length=100, null=True),
        ),
    ]
