# Generated by Django 3.0.6 on 2020-10-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0011_auto_20201020_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignstudentapplicationform',
            name='status',
            field=models.CharField(choices=[('Process', 'İşlem Sırasında'), ('Ensitu', 'Ensitu İncelemesinde'), ('Department', 'Departman İncelemesinde'), ('EnsituDirector', 'Ensitu Direktörünün İncelemesinde'), ('Advisor', 'Danışman İncelemesinde')], default='Process', max_length=100, null=True),
        ),
    ]
