# Generated by Django 3.0.8 on 2020-11-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0014_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignstudentapplicationform',
            name='status',
            field=models.CharField(choices=[('Process', 'İşlem Sırasında'), ('Mistaken', 'Hatalı'), ('Ensitu', 'Ensitu İncelemesinde'), ('Department', 'Departman İncelemesinde'), ('EnsituDirector', 'Ensitu Direktörünün İncelemesinde'), ('Advisor', 'Danışman İncelemesinde')], default='Process', max_length=100, null=True),
        ),
    ]
